backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "products"
    label: "Προϊόντα"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "Τίτλος", name: "title", widget: "string"}
            - {label: "Φωτογραφία", name: "image", widget: "image"}
            - {label: "Τιμή", name: "price", widget: "string"}
            - {label: "Περιγραφή", name: "body", widget: "markdown"}
